# Generated by Django 4.0.3 on 2022-06-27 17:28

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('subfactory', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('queries', models.CharField(blank=True, max_length=1000, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('mobileNo', models.CharField(blank=True, max_length=13, null=True)),
                ('mail', models.CharField(blank=True, max_length=1000, null=True)),
                ('engmobileNo', models.CharField(blank=True, max_length=13, null=True)),
                ('engmail', models.CharField(blank=True, max_length=1000, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('uploadFile', models.FileField(blank=True, null=True, upload_to='')),
                ('admindesc', models.CharField(blank=True, max_length=10000, null=True)),
                ('issueReport', models.CharField(blank=True, max_length=10000, null=True)),
                ('problemDesc', models.CharField(blank=True, max_length=10000, null=True)),
                ('causeProb', models.CharField(blank=True, max_length=10000, null=True)),
                ('solGiven', models.CharField(blank=True, max_length=10000, null=True)),
                ('notes', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('userId', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=5000, unique=True)),
                ('mobNo', models.CharField(max_length=13)),
                ('address', models.TextField(max_length=2000)),
                ('designation', models.CharField(max_length=200)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='is superadmin')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
                ('is_engineer', models.BooleanField(default=False, verbose_name='is engineer')),
                ('is_employee', models.BooleanField(default=False, verbose_name='is employee')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
